"""Add guides table

Revision ID: a7a24637f934
Revises: 93ae563cc497
Create Date: 2025-09-06 15:11:01.785101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a24637f934'
down_revision = '93ae563cc497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name_romanized', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('specialties', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('languages', sa.String(length=255), nullable=True),
    sa.Column('areas', sa.String(length=255), nullable=True),
    sa.Column('price_range', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guides')
    # ### end Alembic commands ###
